development:
  dialect: postgres
  database: vuerecipe_development
  user: postgres
  password: 1234
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:1234@127.0.0.1:5432/vuerecipe_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:1234@127.0.0.1:5432/vuerecipe_production?sslmode=disable"}}
